import Head from "next/head";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Hero from "src/components/Hero";
import Header from "src/components/Header";
import ApplicationForm from "src/components/sections/ApplicationForm";
import Company from "src/components/sections/Company/Index";
import Geo from "src/components/sections/Geo";
import Advantages from "src/components/sections/Advantages";
import PriceList from "src/components/sections/PriceList";
import HowToStart from "src/components/sections/HowToStart";
import SmoothScroll from "src/components/SmoothScroll";

export const getStaticProps = async ({ locale = "rus" }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  };
};
export default function Home() {
  const router = useRouter();
  const { t } = useTranslation("common");

  const switchLanguageHandler = () => {
    const language = router.locale === "en" ? "ru" : "en";
    // eslint-disable-next-line
    router.push(
      { pathname: router.pathname, query: router.query },
      router.asPath,
      { locale: language }
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-jost">
        <SmoothScroll />
        {/* 3d scene and hero */}
        <Header />
        {/* <Hero /> */}
        <Hero />
        <main id="main-content" className="mx-auto max-w-[1550px] px-3 sm:px-5">
          <ApplicationForm />
          <Company />
          <Geo />
          <Advantages />
          <PriceList />
          <HowToStart />
        </main>
      </div>
    </>
  );
}
